// Generated by tools/generate.py; DO NOT EDIT.
namespace SicDic.Core;
public static class Rules
{
    public const string Version = "2025.1.0-draft.1";
    public const string Sha256 = "9b22c103893a46c54189eb17639497d8d1471e1ae9d70f07f01f4909b21119d4";
    public const int SIC_THRESHOLD = 4;
    public const int SIC_COAG_MIN = 2;
    public const int SOFA_MAX = 16;
    public const int DIC_THRESHOLD = 5;
    public const int SIC_MAX = 6;
    public const int DIC_MAX = 8;
    public const string NumberPattern = "[0-9]{1,9}(?:[.,][0-9]{1,6})?";
    public const decimal fibrinogenMgDlPerGL = 100m;
    public const decimal bilirubinUmolPerMgDl = 17.1m;
    public const decimal creatinineUmolPerMgDl = 88.4m;
    public static int sicPlatelets(decimal value, decimal scale)
    {
        if (value < 100m * scale) return 2;
        if (value < 150m * scale) return 1;
        return 0;
    }
    public static int sicInr(decimal value, decimal scale)
    {
        if (value > 1.4m * scale) return 2;
        if (value > 1.2m * scale) return 1;
        return 0;
    }
    public static int sicSofa(decimal value, decimal scale)
    {
        if (value >= 2m * scale) return 2;
        if (value >= 1m * scale) return 1;
        return 0;
    }
    public static int dicPlatelets(decimal value, decimal scale)
    {
        if (value < 50m * scale) return 2;
        if (value < 100m * scale) return 1;
        return 0;
    }
    public static int dicDimer(decimal value, decimal scale)
    {
        if (value > 7m * scale) return 3;
        if (value > 3m * scale) return 2;
        return 0;
    }
    public static int dicPt(decimal value, decimal scale)
    {
        if (value >= 6m * scale) return 2;
        if (value >= 3m * scale) return 1;
        return 0;
    }
    public static int dicFibrinogen(decimal value, decimal scale)
    {
        if (value < 1m * scale) return 1;
        return 0;
    }
    public static int respiratoryUnsupported(decimal value, decimal scale)
    {
        if (value < 300m * scale) return 2;
        if (value < 400m * scale) return 1;
        return 0;
    }
    public static int respiratorySupported(decimal value, decimal scale)
    {
        if (value < 100m * scale) return 4;
        if (value < 200m * scale) return 3;
        if (value < 300m * scale) return 2;
        if (value < 400m * scale) return 1;
        return 0;
    }
    public static int hepaticMgDl(decimal value, decimal scale)
    {
        if (value >= 12m * scale) return 4;
        if (value >= 6m * scale) return 3;
        if (value >= 2m * scale) return 2;
        if (value >= 1.2m * scale) return 1;
        return 0;
    }
    public static int renalMgDl(decimal value, decimal scale)
    {
        if (value >= 5m * scale) return 4;
        if (value >= 3.5m * scale) return 3;
        if (value >= 2m * scale) return 2;
        if (value >= 1.2m * scale) return 1;
        return 0;
    }
    public static int urine24h(decimal value, decimal scale)
    {
        if (value < 200m * scale) return 4;
        if (value < 500m * scale) return 3;
        return 0;
    }
    public static int map(decimal value, decimal scale)
    {
        if (value < 70m * scale) return 1;
        return 0;
    }
    public static int dopamine(decimal value, decimal scale)
    {
        if (value > 15m * scale) return 4;
        if (value > 5m * scale) return 3;
        if (value > 0m * scale) return 2;
        return 0;
    }
    public static int epinephrine(decimal value, decimal scale)
    {
        if (value > 0.1m * scale) return 4;
        if (value > 0m * scale) return 3;
        return 0;
    }
    public static int dobutamine(decimal value, decimal scale)
    {
        if (value > 0m * scale) return 2;
        return 0;
    }
}
