// Generated by tools/generate.py; DO NOT EDIT.
package org.sicdic.core;
public final class Rules {
    private Rules() {}
    public static final String VERSION = "2025.1.0-draft.1";
    public static final String SHA256 = "9b22c103893a46c54189eb17639497d8d1471e1ae9d70f07f01f4909b21119d4";
    public static final int SIC_THRESHOLD = 4;
    public static final int SIC_COAG_MIN = 2;
    public static final int SOFA_MAX = 16;
    public static final int DIC_THRESHOLD = 5;
    public static final int SIC_MAX = 6;
    public static final int DIC_MAX = 8;
    public static final String NUMBER_PATTERN = "[0-9]{1,9}(?:[.,][0-9]{1,6})?";
    public static final java.math.BigDecimal fibrinogenMgDlPerGL = new java.math.BigDecimal("100");
    public static final java.math.BigDecimal bilirubinUmolPerMgDl = new java.math.BigDecimal("17.1");
    public static final java.math.BigDecimal creatinineUmolPerMgDl = new java.math.BigDecimal("88.4");
    public static int sicPlatelets(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("100").multiply(scale)) < 0) return 2;
        if (value.compareTo(new java.math.BigDecimal("150").multiply(scale)) < 0) return 1;
        return 0;
    }
    public static int sicInr(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("1.4").multiply(scale)) > 0) return 2;
        if (value.compareTo(new java.math.BigDecimal("1.2").multiply(scale)) > 0) return 1;
        return 0;
    }
    public static int sicSofa(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("2").multiply(scale)) >= 0) return 2;
        if (value.compareTo(new java.math.BigDecimal("1").multiply(scale)) >= 0) return 1;
        return 0;
    }
    public static int dicPlatelets(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("50").multiply(scale)) < 0) return 2;
        if (value.compareTo(new java.math.BigDecimal("100").multiply(scale)) < 0) return 1;
        return 0;
    }
    public static int dicDimer(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("7").multiply(scale)) > 0) return 3;
        if (value.compareTo(new java.math.BigDecimal("3").multiply(scale)) > 0) return 2;
        return 0;
    }
    public static int dicPt(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("6").multiply(scale)) >= 0) return 2;
        if (value.compareTo(new java.math.BigDecimal("3").multiply(scale)) >= 0) return 1;
        return 0;
    }
    public static int dicFibrinogen(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("1").multiply(scale)) < 0) return 1;
        return 0;
    }
    public static int respiratoryUnsupported(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("300").multiply(scale)) < 0) return 2;
        if (value.compareTo(new java.math.BigDecimal("400").multiply(scale)) < 0) return 1;
        return 0;
    }
    public static int respiratorySupported(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("100").multiply(scale)) < 0) return 4;
        if (value.compareTo(new java.math.BigDecimal("200").multiply(scale)) < 0) return 3;
        if (value.compareTo(new java.math.BigDecimal("300").multiply(scale)) < 0) return 2;
        if (value.compareTo(new java.math.BigDecimal("400").multiply(scale)) < 0) return 1;
        return 0;
    }
    public static int hepaticMgDl(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("12").multiply(scale)) >= 0) return 4;
        if (value.compareTo(new java.math.BigDecimal("6").multiply(scale)) >= 0) return 3;
        if (value.compareTo(new java.math.BigDecimal("2").multiply(scale)) >= 0) return 2;
        if (value.compareTo(new java.math.BigDecimal("1.2").multiply(scale)) >= 0) return 1;
        return 0;
    }
    public static int renalMgDl(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("5").multiply(scale)) >= 0) return 4;
        if (value.compareTo(new java.math.BigDecimal("3.5").multiply(scale)) >= 0) return 3;
        if (value.compareTo(new java.math.BigDecimal("2").multiply(scale)) >= 0) return 2;
        if (value.compareTo(new java.math.BigDecimal("1.2").multiply(scale)) >= 0) return 1;
        return 0;
    }
    public static int urine24h(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("200").multiply(scale)) < 0) return 4;
        if (value.compareTo(new java.math.BigDecimal("500").multiply(scale)) < 0) return 3;
        return 0;
    }
    public static int map(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("70").multiply(scale)) < 0) return 1;
        return 0;
    }
    public static int dopamine(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("15").multiply(scale)) > 0) return 4;
        if (value.compareTo(new java.math.BigDecimal("5").multiply(scale)) > 0) return 3;
        if (value.compareTo(new java.math.BigDecimal("0").multiply(scale)) > 0) return 2;
        return 0;
    }
    public static int epinephrine(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("0.1").multiply(scale)) > 0) return 4;
        if (value.compareTo(new java.math.BigDecimal("0").multiply(scale)) > 0) return 3;
        return 0;
    }
    public static int dobutamine(java.math.BigDecimal value, java.math.BigDecimal scale) {
        if (value.compareTo(new java.math.BigDecimal("0").multiply(scale)) > 0) return 2;
        return 0;
    }
}
