"""Deterministically generate platform rule tables and TSV fixtures. No clinical decisions here."""
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
raw = (ROOT / 'clinical-spec/clinical-rules.json').read_bytes()
r = json.loads(raw)
sha = hashlib.sha256(raw).hexdigest()
outputs = {}
java = ['// Generated by tools/generate.py; DO NOT EDIT.', 'package org.sicdic.core;', 'public final class Rules {', '    private Rules() {}', f'    public static final String VERSION = "{r["version"]}";', f'    public static final String SHA256 = "{sha}";']
cs = ['// Generated by tools/generate.py; DO NOT EDIT.', 'namespace SicDic.Core;', 'public static class Rules', '{', f'    public const string Version = "{r["version"]}";', f'    public const string Sha256 = "{sha}";']
constants = {'SIC_THRESHOLD': r['sic']['threshold'], 'SIC_COAG_MIN': r['sic']['coagulationExclusiveMinimum'], 'SOFA_MAX':r['sic']['sofaMaximum'], 'DIC_THRESHOLD':r['dic']['threshold'], 'SIC_MAX':r['sic']['maximum'], 'DIC_MAX':r['dic']['maximum']}
for name,v in constants.items():
    java.append(f'    public static final int {name} = {v};')
    cs.append(f'    public const int {name} = {v};')
pattern = '[0-9]{1,' + str(r['numeric']['maxIntegerDigits']) + '}(?:[.,][0-9]{1,' + str(r['numeric']['maxFractionDigits']) + '})?'
java.append(f'    public static final String NUMBER_PATTERN = "{pattern}";')
cs.append(f'    public const string NumberPattern = "{pattern}";')
for name,v in r['conversions'].items():
    java.append(f'    public static final java.math.BigDecimal {name} = new java.math.BigDecimal("{v}");')
    cs.append(f'    public const decimal {name} = {v}m;')
for name,bands in r['bands'].items():
    java.append(f'    public static int {name}(java.math.BigDecimal value, java.math.BigDecimal scale) {{')
    cs.append(f'    public static int {name}(decimal value, decimal scale)\n    {{')
    for op,threshold,points in bands:
        if op == 'always':
            java.append(f'        return {points};'); cs.append(f'        return {points};')
        else:
            oper={'lt':'<','le':'<=','gt':'>','ge':'>='}[op]
            java.append(f'        if (value.compareTo(new java.math.BigDecimal("{threshold}").multiply(scale)) {oper} 0) return {points};')
            cs.append(f'        if (value {oper} {threshold}m * scale) return {points};')
    java.append('    }');cs.append('    }')
java.append('}');cs.append('}')
outputs['android/core/src/main/java/org/sicdic/core/Rules.java']='\n'.join(java)+'\n'
outputs['windows/SicDic.Core/Rules.g.cs']='\n'.join(cs)+'\n'
rows=[]
for p in sorted((ROOT/'shared-test-vectors').glob('*-tests.json')):
    for t in json.loads(p.read_text()):
        rows.append('\t'.join([t['id'],t['operation'],*t['input'],t['expected']]))
outputs['shared-test-vectors/generated/vectors.tsv']='\n'.join(rows)+'\n'
for name,content in outputs.items():
    path=ROOT/name
    if '--check' in sys.argv:
        if not path.exists() or path.read_text()!=content:
            raise SystemExit('Generated file stale: '+name)
    else:
        path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
print(f'Rules SHA256: {sha}; {len(rows)} shared vectors; generated files '+('verified' if '--check' in sys.argv else 'written'))
